"""
Embed scraped data as JS globals so index.html works from file:// (no fetch, no server).

Reads:  raw/groups.json, data/bots.json, data/fights.json, raw/fan_comments.json
Writes: data/data.js  (window.OOF_DATA = {...})

Run: python3 3_embed.py
"""

import json


def main():
    with open("raw/groups.json") as f:
        groups = json.load(f)
    with open("data/bots.json") as f:
        bots = json.load(f)
    with open("data/fights.json") as f:
        fights = json.load(f)

    try:
        with open("raw/fan_comments.json") as f:
            comments = json.load(f)
    except FileNotFoundError:
        comments = []

    # Per-bot fan flavor: short, high-scored comment snippets mentioning exactly one bot.
    # Kept small — these feed the prompt for crowd-reaction color, never shown raw (spoilers).
    flavor = {}
    for c in sorted(comments, key=lambda c: -c.get("score", 0)):
        mentioned = c.get("bots_mentioned", [])
        if len(mentioned) != 1:
            continue
        bot = mentioned[0]
        text = c.get("text", "").strip()
        if not text or len(text) > 200:
            continue
        flavor.setdefault(bot, [])
        if len(flavor[bot]) < 3:
            flavor[bot].append(text)

    payload = {
        "season": groups["season"],
        "groups": groups["groups"],
        "bots": bots,
        "fights": fights,
        "matchups": groups["matchups"],
        "fan_flavor": flavor,
    }

    with open("prompts/beats_system.txt") as f:
        system_prompt = f.read()

    with open("data/data.js", "w") as f:
        f.write("// Generated by 3_embed.py - do not edit by hand\n")
        f.write("window.OOF_DATA = ")
        json.dump(payload, f)
        f.write(";\n")
        f.write("window.OOF_SYSTEM_PROMPT = ")
        json.dump(system_prompt, f)
        f.write(";\n")

    print(f"data/data.js: {len(bots)} bots, {len(fights)} fights, fan flavor for {len(flavor)} bots")


if __name__ == "__main__":
    main()
